### ISSUE TITLE
"galaxy server message queue init failed"

### ISSUE THREAD

**Issue by sshaikh** [SanderSchutten/XiaomiXiaofangFirmware#34]
I see this on the web ui, and can not see any streams in VLC.

**Comment by GrumpyMeow** [comment]
I suspect Sonix-Proj is not running..
Could you recheck if thats the case?

Op 24 mei 2017 om 19:38 heeft sshaikh <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


I see this on the web ui, and can not see any streams in VLC.

**Comment by sshaikh** [comment]
Could you please outline instructions? Ps -al or something?

**Comment by GrumpyMeow** [comment]
Check with: ps -aux | grep proj
Restart with:
/bin/sonix-proj

Op 25 mei 2017 om 12:23 heeft sshaikh <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


Could you please outline instructions? Ps -al or something?

**Comment by sshaikh** [comment]
It wasn't present and /bin/sonix-proj did the trick. All working now.

Do you need me to send you any logs or debugging to fix this?

**Comment by GrumpyMeow** [comment]
Thank you. But at this moment there are stil a lot of issues to be fixed. The firmware isn't stable yet.

Op 25 mei 2017 om 13:59 heeft sshaikh <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


It wasn't present and /bin/sonix-proj did the trick. All working now.

Do you need me to send you any logs or debugging to fix this?
