### ISSUE TITLE
Copy of SN986_1.60_QR_Scan_019a_20160606_0951.tgz

### ISSUE THREAD

**Issue by randomiq** [SanderSchutten/XiaomiXiaofangFirmware#40]
Not an issue, but more a question, where can one get SN986_1.60_QR_Scan_019a_20160606_0951.tgz that is referenced?

**Comment by gipsh** [comment]
https://mega.nz/#!cnJDHQBS

**Comment by randomiq** [comment]
Is there a decryption key available somewhere?

**Comment by randomiq** [comment]
Thanks
